NPC_MESSAGE_COUNT_00 = 2
NPC_MESSAGE_COUNT_01 = 2
NPC_MESSAGE_COUNT_02 = 2
NPC_MESSAGE_COUNT = [NPC_MESSAGE_COUNT_00, NPC_MESSAGE_COUNT_01, NPC_MESSAGE_COUNT_02]

NPC_MESSAGE_LIST_1 = [
    ("할머니", "그냥 해줘잉!"),
    ("밍쥬", "힝..넹"),
]

NPC_MESSAGE_LIST_2 = [
    ("대표님", "이것도 해줘잉!"),
    ("밍쥬", "힝..넵"),
]

NPC_MESSAGE_LIST = [
    NPC_MESSAGE_LIST_1,
    NPC_MESSAGE_LIST_2,
]

NPC_STAGE_CNT0 = 2
NPC_STAGE_CNT1 = 1

NPC_STAGE_CNT = [
    NPC_STAGE_CNT0,
    NPC_STAGE_CNT1,
]